//Everything in this files is generated by LLM 

export function enigmaMainMenuUI(): void {
    console.log("\n╔══════════════════════════════════════════════════════╗");
    console.log("║                                                      ║");
    console.log("║           ███████╗███╗   ██╗██╗███╗   ███╗           ║");
    console.log("║           ██╔════╝████╗  ██║██║████╗ ████║           ║");
    console.log("║           █████╗  ██╔██╗ ██║██║██╔████╔██║           ║");
    console.log("║           ██╔══╝  ██║╚██╗██║██║██║╚██╔╝██║           ║");
    console.log("║           ███████╗██║ ╚████║██║██║ ╚═╝ ██║           ║");
    console.log("║           ╚══════╝╚═╝  ╚═══╝╚═╝╚═╝     ╚═╝           ║");
    console.log("║                                                      ║");
    console.log("║             Terminal Enigma Machine v1.0             ║");
    console.log("║                                                      ║");
    console.log("║   [1] Configure Rotors                               ║");
    console.log("║   [2] Set Plugboard                                  ║");
    console.log("║   [3] Encrypt / Decrypt Message                      ║");
    console.log("║   [4] View Machine Status                            ║");
    console.log("║   [5] Exit                                           ║");
    console.log("║                                                      ║");
    console.log("╚══════════════════════════════════════════════════════╝");
}

export function encryptUI(): void {
    console.log("\n\nWould you like to:")
    console.log("[1] Enter another message");
    console.log("[2] Return to Main Menu");
}

export function rotorConfigUI(): void {
    console.log("\nWould you like to:")
    console.log("[1] Reconfigure the rotors");
    console.log("[2] Return to Main Menu");
}





module.exports = { enigmaMainMenuUI, encryptUI, rotorConfigUI }