
import * as readline from "readline";
import { encryptUI, enigmaMainMenuUI, rotorConfigUI } from "./enigmaUI";
import { rawListeners } from "process";
import { machine } from "os";

export type PlugBoard = Array<number>;
export type NumerisedString = Array<number>;
export type RotorHouse = Array<Rotor>;
type Reflector = Array<number>;
type RotorInternal = Array<number>;
type Rotor = [number, RotorInternal];
//Premade arrays for the machine
const rotor1: RotorInternal = [12, 3, 21, 0, 8, 25, 5, 19, 1, 14, 24, 7, 17, 23, 6, 20, 13, 2, 11, 4, 22, 10, 18, 15, 9, 16];
const rotor2: RotorInternal = [4, 16, 1, 23, 12, 9, 0, 18, 7, 25, 14, 3, 21, 10, 6, 20, 11, 2, 24, 15, 19, 5, 22, 13, 17, 8];
const rotor3: RotorInternal = [8, 22, 3, 19, 1, 11, 24, 0, 16, 7, 25, 14, 2, 18, 5, 21, 4, 10, 6, 23, 13, 15, 12, 20, 17, 9];

//An array where the numbers are swapped in pairs meaning reflector[i] == y && reflector[y] == i
const reflector: Reflector = [17, 9, 5, 14, 23, 2, 24, 19, 21, 1, 15, 13, 22, 11, 3, 10, 18, 0, 16, 7, 25, 8, 12, 4, 6, 20];
const basePlug: PlugBoard = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25];


const zeroIndex: number = 97;

/**
 * Converts input to an array of each individual characters corresponding number (0-25)
 * @param inputString The string that should be converted
 * @returns Array of converted characters and null if failed (triggered by non letters being input)
 */
function stringToNumber(inputChar: string): number | null {
    let lowerCaseInput: string = inputChar.toLowerCase();

    //Regex in this line generated by LLM
    if (!/^[a-z]+$/.test(lowerCaseInput)) {
        return null;
    }
        
    return lowerCaseInput.charCodeAt(0) - zeroIndex; // Returns the zero indexed numerised char
}

function numberToString(input: number): string {
    return String.fromCharCode(input + zeroIndex); // Returns the zero indexed numerised char
}

function mappingAction(map: Array<number>, input: number): number {
    return map[input];
}

//Only for abstraction in main function
function plugBoardAction(plugBoard: PlugBoard, input: number): number {
    return mappingAction(plugBoard, input);
}

function reflectorAction(reflector: Reflector, input: number): number {
    return mappingAction(reflector, input);
}

function rotorActionForward(rotor: Rotor, input: number): number {
    return mappingAction(rotor[1], input);
}

function rotorActionBackward(rotor: Rotor, input: number): number {
    return rotor[1].indexOf(input);
}


//Initializes the rotor house
function rotorHouseInit(): RotorHouse {
    return [[0, rotor1], [0, rotor2], [0, rotor3]];
}

//Initializes the plugboard
function plugBoardInit(): PlugBoard {
    return basePlug;
}

function displayPlugBoard(plugBoard: PlugBoard): string {
    let donePairs: Array<number> = new Array<number>;
    let unboundLetters: string = "Available letters:\n";
    let pluggedLetters: string = "Current plugs:\n";
    const plug: string = "<->";
    for (let i = 0; i < plugBoard.length; i++) {
        if (plugBoard[i] == i) {
            unboundLetters = unboundLetters + numberToString(i) + " ";
            continue;
        }
        if (donePairs.includes(i)) continue;
        donePairs.push(plugBoard[i]);
        pluggedLetters = pluggedLetters + " " + numberToString(i) + plug + numberToString(plugBoard[i]);
    }
    return pluggedLetters.toUpperCase() + "\n" + unboundLetters.toUpperCase();
}

function displayRotors(rotorHouse: RotorHouse): string {
    let displayedRotors: string = "Current Rotor configuration:\n";
    for (let i = 0; i < rotorHouse.length; i++) {
        displayedRotors = displayedRotors + (rotorHouse[i][0] + 1) + " ";
    }
    return displayedRotors;
}

//Helper func for rotorAction
function rotateRotor(rotor: Rotor, steps: number) {
    rotor[0] = Math.abs(((rotor[0] + steps) % 25));
    rotor[1] = rotor[1].slice(steps % 25).concat(rotor[1].slice(0, steps % 25));
}

//Routes the input through the 3 rotors, into the reflector then in reverse order back through said reflectors
function rotorReflectorRouting(rotorHouse: RotorHouse, input: number): number {
    let routeOutput: number = input;
    //First pass through rotor house
    routeOutput = rotorActionForward(rotorHouse[0], routeOutput);
    routeOutput = rotorActionForward(rotorHouse[1], routeOutput);
    routeOutput = rotorActionForward(rotorHouse[2], routeOutput);

    //goes through reflector
    routeOutput = reflectorAction(reflector, routeOutput);

    //Second pass through rotor house in oposite order
    routeOutput = rotorActionBackward(rotorHouse[2], routeOutput);
    routeOutput = rotorActionBackward(rotorHouse[1], routeOutput);
    routeOutput = rotorActionBackward(rotorHouse[0], routeOutput);

    return routeOutput;
}

//Rotates the rotors to their corresponding place and calls the routing function
function rotorReflectorAction(rotorHouse: RotorHouse, input: number): number {
    rotateRotor(rotorHouse[0], 1);
    if (rotorHouse[0][0] != 0) {
        return rotorReflectorRouting(rotorHouse, input);
    }
    rotateRotor(rotorHouse[1], 1);
    if (rotorHouse[1][0] != 0) {
        return rotorReflectorRouting(rotorHouse, input);
    }
    rotateRotor(rotorHouse[2], 1);
    return rotorReflectorRouting(rotorHouse, input);
}


function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function enigmaMessageHandler(answer: string, rotorHouse: RotorHouse, plugBoard: PlugBoard, rl: readline.Interface) {
    //Regex in this line generated by LLM
    let answerNoSpaces = answer.replace(/\s+/g, "");
    let enigmaOutput: number | null;
    for (let i = 0; i < answerNoSpaces.length; i++) {
        enigmaOutput = stringToNumber(answerNoSpaces[i]);
        if (enigmaOutput == null) {
            process.stdout.write(answerNoSpaces[i]);
            continue;
        }
        enigmaOutput = plugBoardAction(plugBoard, enigmaOutput);
        enigmaOutput = rotorReflectorAction(rotorHouse, enigmaOutput);
        enigmaOutput = plugBoardAction(plugBoard, enigmaOutput);
        //TODO: replace this with readline
        process.stdout.write(numberToString(enigmaOutput));
        await sleep(100);
    }
}

function questionAsync(rl: readline.Interface, query: string): Promise<string> {
    return new Promise((resolve) => {
        rl.question(query, resolve);
    });
}

function clearAboveLine() {
    //Found these 2 lines on stackoverflow 
    readline.moveCursor(process.stdout, 0, -1); 
    readline.clearLine(process.stdout, 0); 
}

async function waitForMenuKeypress(options: Array<string>, rl: readline.Interface): Promise<string> {
    return new Promise(async (resolve) => {
        while (true) {
            const answer = await questionAsync(rl, "");
            if (options.includes(answer)) {
                clearAboveLine();
                resolve(answer);
                break;
            }
            clearAboveLine();
        }
    });
}


async function configurePlugBoard(plugBoard: PlugBoard, rl: readline.Interface) {
    while (true) {
        try {
            const answer = await questionAsync(rl, "Enter pairs of letters separated by a space to pair said letters (max pairs: 10). Ex: 'ab cd ef'\n");
            parseAndApply(answer);
            console.log("Success!")
            await questionAsync(rl, "Press 'enter' to return to menu");
            return;
        } catch (error) {
            if (error instanceof Error) {
                console.log("Error:", error.message);
                await questionAsync(rl, "");
                continue;
            } else {
                console.log("Something went wrong");
                return;
            }
        }
    }

    function parseAndApply(answer: string) {
        //Regex generated by LLM
        const plugPairs: Array<string> = answer.split(/\s+/);
        if (plugPairs.length > 10) throw new Error("Max number of pairs allowed is 10");

        for (let i = 0; i < plugPairs.length; i++) {
            if (plugPairs[i].length != 2) throw new Error("Only pairs of letters allowed");

            let leftChar = stringToNumber(plugPairs[i][0]);
            let rightChar = stringToNumber(plugPairs[i][1]);

            

            if (leftChar == null || rightChar == null) throw new Error("Pair(s) contains something other than letters (a-z)");
            //Unbind
            if (leftChar == rightChar) {
                rightChar = plugBoard[leftChar];
                plugBoard[leftChar] = leftChar;
                plugBoard[rightChar] = rightChar;
                continue;
            }
            plugBoard[leftChar] = rightChar;
            plugBoard[rightChar] = leftChar;
        }
    }
}


async function configureRotors(rotorHouse: RotorHouse, rl: readline.Interface): Promise<boolean> {
    //TODO: error handling in this function
    const answer = await questionAsync(rl, "Enter each rotor position (1-26) separated by a space. Ex: '10 5 24'\n");
    //Regex in this line generated by LLM
    const rotorPos: Array<string> = answer.split(/\s+/);
    for (let i = 0; i < rotorHouse.length; i++) {
        rotateRotor(rotorHouse[i], Math.abs((rotorHouse[i][0] - (Number(rotorPos[i]) - 1)) % 25));
    }
    console.log("Updated positions to: ", rotorPos[0], " ", rotorPos[1], " ", rotorPos[2]);
    rotorConfigUI();
    const menuAnswer: string = await waitForMenuKeypress(['1', '2'], rl);
    switch (menuAnswer) {
    case '1':
        return true;
    case '2':
        return false;
    default:
        process.exit(420);
    }
}


//Starts encryption/decryption
async function runEncryption(rotorHouse: RotorHouse, plugBoard: PlugBoard, rl: readline.Interface): Promise<boolean> {
    const answer = await questionAsync(rl, "Input:\n");
    console.log("Output:");
    await enigmaMessageHandler(answer, rotorHouse, plugBoard, rl);
    encryptUI();
    const menuAnswer: string = await waitForMenuKeypress(['1', '2'], rl);
    switch (menuAnswer) {
    case '1':
        return true;
    case '2':
        return false;
    default:
        process.exit(420);
    }
}


async function machineStatus(rotorHouse: RotorHouse, plugBoard: PlugBoard, rl: readline.Interface) {
    console.log(displayRotors(rotorHouse));
    console.log(displayPlugBoard(plugBoard));
    await questionAsync(rl, "\nPress 'enter' to return to menu");
}


//Launches main menu
async function enigmaMainMenu(rotorHouse: RotorHouse, plugBoard: PlugBoard, rl: readline.Interface) {
    while (true) {
        enigmaMainMenuUI();
        const menuAnswer: string = await waitForMenuKeypress(['1', '2', '3', '4', '5'], rl);
        switch (menuAnswer) {
            case '1':
                while (await configureRotors(rotorHouse, rl));
                break;
            case '2':
                await configurePlugBoard(plugBoard, rl);
                break;
            case '3':
                while (await runEncryption(rotorHouse, plugBoard, rl));
                break;
            case '4':
                await machineStatus(rotorHouse, plugBoard, rl);
                break;
            case '5':

                rl.close();
                console.clear();
                process.exit(0);
            default:
                process.exit(420);
        }
    }
}


//The main function launching the enigma machine
function main() {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
    });
    let rotorHouse: RotorHouse = rotorHouseInit();
    let plugBoard: PlugBoard = plugBoardInit();
    console.clear();
    enigmaMainMenu(rotorHouse, plugBoard, rl);
}


main();



module.exports = { stringToNumber, plugBoardAction, rotorReflectorAction, rotorHouseInit };